In [2]:
from IPython.display import Latex

import numpy as np
import pandas as pd


from IPython.display import HTML, Math, Latex

In [3]:
def l(string):
    display_latex(string, raw=True)


def podushny(C, b):
    podushny = np.full_like(b, 0.0, dtype=np.double)
    
    for i in range(len(b)):
        lamb = (C - podushny.sum()) / (len(b) - i)
        
        
        if lamb >= b[i]:
            print( "$\lambda_{1} = \dfrac{C-}{n-{2}}$" % ())
            podushny[i] = b[i]
            continue

        podushny[i:] = lamb
        break

    return podushny


def rivnevy(C, b):
    rivnevy = np.full_like(b, 0.0, dtype=np.double)

    for i in range(len(b)):
        lamb = (1 / (len(b) - i)) * (b[i:].sum() - C)
        if lamb >= b[i]:
            rivnevy[i] = 0
            continue

        rivnevy[i:] = b[i:] - lamb
        break


    return rivnevy


def nCore(C, b):
    core = np.full_like(b, 0.0, dtype=np.double)

    """ default case C > b.sum()/2"""

    def nCoreLess(C, b, core):
        for i in range(len(b)):
            lamb = (C - core.sum()) / (len(b) - i)
            if lamb > b[i]/2:
                core[i] = b[i]/2
                continue
            core[i:] = lamb
            break
        return core

    def nCoreMore(C, b, core):

        for i in range(len(b)):
            lamb = (1/(len(b)-i)) * (b.sum() - C - core.sum())
            if lamb > b[i]/2:
                core[i] = b[i]/2
                continue

            core[i:] = b[i:] - lamb
            break

        return core

    return (nCoreLess if C < b.sum()/2 else nCoreMore)(C, b, core)

def proportional(C, b):
    return b * C/b.sum()


def report(C, b):
    df = pd.DataFrame(data=Profits, columns = ["Dohody"])
    df['Podushny']      = podushny(C, b)
    df['Rivnevy']       = rivnevy(C, b)
    df['n-Core']        = nCore(C, b)
    df['Proportional']  = proportional(C, b)

    df = df.T
    df['Total'] = df.sum(axis=1)
    return display(df)

# Контрольна робота 8

## 1.1

In [3]:
Profits = np.array([ 4, 8, 12, 20, 26 ])
Cs = np.array([30, 50])

In [4]:
report(30, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$


0         1          2          3          4  Total
Dohody        4.000000  8.000000  12.000000  20.000000  26.000000   70.0
Podushny      4.000000  6.500000   6.500000   6.500000   6.500000   30.0
Rivnevy       0.000000  0.000000   2.666667  10.666667  16.666667   30.0
n-Core        2.000000  4.000000   6.000000   9.000000   9.000000   30.0
Proportional  1.714286  3.428571   5.142857   8.571429  11.142857   30.0

In [5]:
report(50, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0         1          2          3          4  Total
Dohody        4.000000  8.000000  12.000000  20.000000  26.000000   70.0
Podushny      4.000000  8.000000  12.000000  13.000000  13.000000   50.0
Rivnevy       0.000000  4.000000   8.000000  16.000000  22.000000   50.0
n-Core        2.000000  4.000000   7.333333  15.333333  21.333333   50.0
Proportional  2.857143  5.714286   8.571429  14.285714  18.571429   50.0

## 1.2

In [6]:
property_cost = 15000
lenders = np.array([6000, 8000, 10000])

In [7]:
nCore(property_cost, lenders)

array([3000., 5000., 7000.])

## 2.1

In [8]:
Profits = np.array([ 10, 12, 18, 20, 30 ])

In [9]:
report(45, Profits)

0     1     2     3     4  Total
Dohody        10.0  12.0  18.0  20.0  30.0   90.0
Podushny       9.0   9.0   9.0   9.0   9.0   45.0
Rivnevy        1.0   3.0   9.0  11.0  21.0   45.0
n-Core         5.0   6.0   9.0  10.0  15.0   45.0
Proportional   5.0   6.0   9.0  10.0  15.0   45.0

In [10]:
report(75, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0     1          2          3          4  Total
Dohody        10.000000  12.0  18.000000  20.000000  30.000000   90.0
Podushny      10.000000  12.0  17.666667  17.666667  17.666667   75.0
Rivnevy        7.000000   9.0  15.000000  17.000000  27.000000   75.0
n-Core         7.000000   9.0  15.000000  17.000000  27.000000   75.0
Proportional   8.333333  10.0  15.000000  16.666667  25.000000   75.0

## 2.2

In [11]:
property_cost = 10000
lenders = np.array([4000, 6000, 8000])

In [12]:
nCore(property_cost, lenders)

array([2000., 3000., 5000.])

## 3.1

In [13]:
Profits = np.array([ 6, 10, 14, 20, 24 ])

In [14]:
report(30, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$


0          1          2          3         4  Total
Dohody        6.000000  10.000000  14.000000  20.000000  24.00000   74.0
Podushny      6.000000   6.000000   6.000000   6.000000   6.00000   30.0
Rivnevy       0.000000   0.500000   4.500000  10.500000  14.50000   30.0
n-Core        3.000000   5.000000   7.000000   7.500000   7.50000   30.0
Proportional  2.432432   4.054054   5.675676   8.108108   9.72973   30.0

In [15]:
report(60, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0          1          2          3          4  Total
Dohody        6.000000  10.000000  14.000000  20.000000  24.000000   74.0
Podushny      6.000000  10.000000  14.000000  15.000000  15.000000   60.0
Rivnevy       3.200000   7.200000  11.200000  17.200000  21.200000   60.0
n-Core        3.200000   7.200000  11.200000  17.200000  21.200000   60.0
Proportional  4.864865   8.108108  11.351351  16.216216  19.459459   60.0

## 3.2

In [16]:
property_cost = 12000
lenders = np.array([6000, 8000, 12000])

In [17]:
nCore(property_cost, lenders)

array([3000., 4000., 5000.])

## 4.1

In [18]:
Profits = np.array([ 8, 12, 20, 24, 32 ])
Cs = np.array([36, 70])

In [19]:
report(36, Profits)

0     1          2          3          4  Total
Dohody        8.0  12.0  20.000000  24.000000  32.000000   96.0
Podushny      7.2   7.2   7.200000   7.200000   7.200000   36.0
Rivnevy       0.0   0.0   6.666667  10.666667  18.666667   36.0
n-Core        4.0   6.0   8.666667   8.666667   8.666667   36.0
Proportional  3.0   4.5   7.500000   9.000000  12.000000   36.0

In [20]:
report(70, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0      1          2          3          4  Total
Dohody        8.000000  12.00  20.000000  24.000000  32.000000   96.0
Podushny      8.000000  12.00  16.666667  16.666667  16.666667   70.0
Rivnevy       2.800000   6.80  14.800000  18.800000  26.800000   70.0
n-Core        4.000000   6.50  14.500000  18.500000  26.500000   70.0
Proportional  5.833333   8.75  14.583333  17.500000  23.333333   70.0

## 4.2

In [21]:
property_cost = 16000
lenders = np.array([4000, 6000, 10000])

In [22]:
nCore(property_cost, lenders)

array([2666.66666667, 4666.66666667, 8666.66666667])

## 5.1

In [23]:
profits = np.array([ 10, 12, 18, 20, 30, 36 ])

In [24]:
report(50, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$


0      1          2     3          4  Total
Dohody        8.000000  12.00  20.000000  24.0  32.000000   96.0
Podushny      8.000000  10.50  10.500000  10.5  10.500000   50.0
Rivnevy       0.000000   2.50  10.500000  14.5  22.500000   50.0
n-Core        4.000000   6.00  10.000000  12.0  18.000000   50.0
Proportional  4.166667   6.25  10.416667  12.5  16.666667   50.0

In [25]:
report(90, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0      1      2     3     4  Total
Dohody        8.0  12.00  20.00  24.0  32.0   96.0
Podushny      8.0  12.00  20.00  24.0  26.0   90.0
Rivnevy       6.8  10.80  18.80  22.8  30.8   90.0
n-Core        6.8  10.80  18.80  22.8  30.8   90.0
Proportional  7.5  11.25  18.75  22.5  30.0   90.0

## 5.2

In [26]:
property_cost = 20000
lenders = np.array([6000, 8000, 10000])

In [27]:
nCore(property_cost, lenders)

array([4666.66666667, 6666.66666667, 8666.66666667])

## 6.1

In [28]:
Profits = np.array([ 4, 8, 12, 20, 26, 30 ])

In [29]:
report(48, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0     1      2     3      4     5  Total
Dohody        4.00  8.00  12.00  20.0  26.00  30.0  100.0
Podushny      4.00  8.00   9.00   9.0   9.00   9.0   48.0
Rivnevy       0.00  0.00   2.00  10.0  16.00  20.0   48.0
n-Core        2.00  4.00   6.00  10.0  13.00  13.0   48.0
Proportional  1.92  3.84   5.76   9.6  12.48  14.4   48.0

In [30]:
report(84, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0         1          2          3          4          5  \
Dohody        4.000000  8.000000  12.000000  20.000000  26.000000  30.000000   
Podushny      4.000000  8.000000  12.000000  20.000000  20.000000  20.000000   
Rivnevy       1.333333  5.333333   9.333333  17.333333  23.333333  27.333333   
n-Core        2.000000  5.200000   9.200000  17.200000  23.200000  27.200000   
Proportional  3.360000  6.720000  10.080000  16.800000  21.840000  25.200000   

              Total  
Dohody        100.0  
Podushny       84.0  
Rivnevy        84.0  
n-Core         84.0  
Proportional   84.0

## 6.2

In [31]:
property_cost = 15000
lenders = np.array([6000, 8000, 10000])

In [32]:
nCore(property_cost, lenders)

array([3000., 5000., 7000.])

## 7.1

In [33]:
profits = np.array([ 6, 10, 14, 20, 24, 36 ])

In [34]:
report(50, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0    1     2     3     4     5  Total
Dohody        4.0  8.0  12.0  20.0  26.0  30.0  100.0
Podushny      4.0  8.0   9.5   9.5   9.5   9.5   50.0
Rivnevy       0.0  0.0   2.5  10.5  16.5  20.5   50.0
n-Core        2.0  4.0   6.0  10.0  13.0  15.0   50.0
Proportional  2.0  4.0   6.0  10.0  13.0  15.0   50.0

In [35]:
report(80, Profits)

$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$
$\lambda_{1} = \dfrac{C-}{n-{2}}$


0         1          2          3          4          5  \
Dohody        4.000000  8.000000  12.000000  20.000000  26.000000  30.000000   
Podushny      4.000000  8.000000  12.000000  18.666667  18.666667  18.666667   
Rivnevy       0.666667  4.666667   8.666667  16.666667  22.666667  26.666667   
n-Core        2.000000  4.400000   8.400000  16.400000  22.400000  26.400000   
Proportional  3.200000  6.400000   9.600000  16.000000  20.800000  24.000000   

              Total  
Dohody        100.0  
Podushny       80.0  
Rivnevy        80.0  
n-Core         80.0  
Proportional   80.0

## 7.2

In [4]:
property_cost = 12000
lenders = np.array([6000, 8000, 12000])

In [5]:
nCore(property_cost, lenders)

array([3000., 4000., 5000.])