# `__code__`

In [1]:
import numpy as np
import sympy as sy

In [2]:
rational = lambda x: sy.Rational(x)

def rm(array):
    """rational matrix """
    return np.array([[rational(x) for x in row] for row in array])

def simple_antagonist(matrix):
    " просте механічне вирішення антагоністичної задачі "
    
    print(matrix.T)
    matrix = (np.diff(matrix.T, axis=0)[0]) * -1
#     matrix = matrix[0] - matrix[1]
    
    print(matrix)
    return (np.array([-matrix[1], matrix[0]]) / (matrix[0] - matrix[1]))

def maxmin(matrix):
    column = [k for k, v in enumerate(matrix[0]) if v == matrix[0].min()]
    return matrix[:, column].max()

In [3]:
# "задача № 1"
# A = [ [ 3,  1], [2, 12], ]
# B = [ [ 9, -2], [-3, 3], ]

# # "задача № 2" 
A = [ [ 4, 1], [-3, 8],]
B = [ [ 6, 4], [ 1, 4],]

# # "задача № 3" - підручний 777
# A = [ [ 6,  -1], [-3, 8], ]
# B = [ [ 10, -4], [-1, 4], ]

# # "задача № 4" на парі
# A = [ [ 8,  3], [-4,  4], ]
# B = [ [ 4,  -1], [1, 10], ]

# НЕНАДІЙНИЙ ПРИКЛАД - приклад нотатки (зошит)
# A = [ [ 8, -3], [-1,12], ]
# B = [ [10,  3], [-5, 4], ]

In [4]:
A = rm(A)
B = rm(B)

## При відсутності коаліції знайти найкращі стратегії обох гравців і відповідні виграші.

In [5]:
# знаходимо наші ікси 
Xs = simple_antagonist(A)

print("-"*10)

# Та ігрики
Ys = simple_antagonist(B.T)

UZirochka = (A.T[0]*Xs).sum()
VZirochka = (B[0]*Ys).sum()

Xs_string = "{}|{}".format(*Xs.tolist()).split("|")
Ys_string = "{}|{}".format(*Ys.tolist()).split("|")

Us = str(UZirochka)
Vs = str(VZirochka)

print( "X1:{1:>5} \t X2:{2:>5} \t U*:{0:>5}".format(Us, *Xs_string) )
print( "Y1:{1:>5} \t Y2:{2:>5} \t V*:{0:>5}".format(Vs, *Ys_string) )
 

[[4 -3]
 [1 8]]
[3 -11]
----------
[[6 4]
 [1 4]]
[5 0]
X1:11/14 	 X2: 3/14 	 U*:  5/2
Y1:    0 	 Y2:    1 	 V*:    4


## У кооперативній грі двох осіб вияснити доцільність створення коаліції і знайти точку Неша.

$$ R = u'+v' $$

$$\overline{u}=\dfrac{(u^*-v^*)+R}{2} \qquad \overline{v'}=\dfrac{(v^*-u^*)+R}{2} $$

$$ \overline{v} = \dfrac{\overline{v'}}{\alpha} $$

In [6]:
topleft, bottomright = A[0][0]+B[0][0], A[1][1]+B[1][1]

"хз що далі?"
assert topleft != bottomright

# print(A)

alpha = (A[0][0] - A[1][1])/-(B[0][0]-B[1][1])
B_shtrih = B * alpha

assert (A[0][0] + B_shtrih[0][0]) ==  (A[1][1] + B_shtrih[1][1])
R = A[0][0] + B_shtrih[0][0]

VZirochka_shtrih = alpha * VZirochka

U_shapka = (UZirochka - VZirochka_shtrih + R )/2

V_shapka_shtrih = (VZirochka_shtrih - UZirochka + R )/2
V_shapka = V_shapka_shtrih / alpha
 

print( "α: {0:>5}".format(str(alpha)) )
print( "=" * 40 )
print( "B'  = " )
print(B_shtrih)

print( "R    = {:>6}".format(str(R)) )
print( "V*'  = {:>6}".format(str(VZirochka_shtrih)) )
print( "U^   = {:>6}".format(str(U_shapka)) )
print( "V^'  = {:>6}".format(str(V_shapka_shtrih)) )
print( "V^   = {:>6}".format(str(V_shapka)) )


mark = VZirochka <= V_shapka
print( "V^ ({}) >= V* ({}) ? {} ".format(str(V_shapka), str(VZirochka), mark))

mark = UZirochka > U_shapka
print( "U^ ({}) >= U* ({}) ? {} ".format(str(U_shapka), str(UZirochka), mark))

α:     2
B'  = 
[[12 8]
 [2 8]]
R    =     16
V*'  =      8
U^   =   21/4
V^'  =   43/4
V^   =   43/8
V^ (43/8) >= V* (4) ? True 
U^ (21/4) >= U* (5/2) ? False 


## Перевірити вплив дії погроз, визначити арбітражний розв’язок у випадку дії погроз і порівняти із точкою Неша.

In [7]:
ABsht = A - B_shtrih 
ABsht

array([[-8, -7],
       [-5, 0]], dtype=object)

In [8]:
ABsht = A - B_shtrih 
XS_y = simple_antagonist(ABsht)

U_y = (ABsht.T[0]*XS_y).sum()

XS_y, U_y

[[-8 -5]
 [-7 0]]
[-1 -5]


(array([5/4, -1/4], dtype=object), -35/4)

In [9]:
u_y = (U_y+R)/2
v_y = (-U_y+R)/2
u_y, v_y, v_y/alpha

(29/8, 99/8, 99/16)